#!/bin/bash -e
. ~/bioehs-django/venv/bin/activate
# cd '/home/b/bi/bioehs/bioehs-django'
PYTHONPATH=~/bioehs-django/bioehswebsite:~/bioehs-django/bioehswebsite/bioehs:$PYTHONPATH \
    exec gunicorn -w 2 -b unix:/srv/apps/$(whoami)/$(whoami).sock \
        --log-file -  bioehs.wsgi
