# Generated by Django 2.0 on 2019-01-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BioEHSLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular_application_form', models.URLField(default='https://docs.google.com/forms/d/e/1FAIpQLSe-WN00gYEY3J6Y62Tey0OdQxo1L2rXuqDxbuf_K1cBJ1GKag/viewform', help_text='TO BE UPDATED EACH SEMESTER', verbose_name='Regular Application Form')),
                ('prospective_member_interest_form', models.URLField(default='https://docs.google.com/forms/d/e/1FAIpQLSeunglCnYuYMrjm_3eLgSTgCfEEMZL99J06VcgwN0gKhVX6Wg/viewform', help_text='TO BE UPDATED EACH SEMESTER', verbose_name='Prospective Member Interest Form')),
                ('outreach_blog', models.URLField(default='https://bioehs.wordpress.com/', help_text='Check with Outreach if this needs to be updated', verbose_name='Outreach Blog')),
                ('bioehsc_progress_form', models.URLField(default='https://docs.google.com/document/u/1/d/1OhZm34D5DUPXlk2CnnXqYgrJzPYh6oJniUn-5yRDXzU/edit', help_text='TO BE UPDATED EACH SPRING', verbose_name='BioEHSC Mentor/Team Progress Form')),
                ('bioehsc_handbook', models.URLField(default='http://bit.ly/2017BioEHSCHandbook', help_text='Check with BioEHSC External Relations/Junior Chair/Senior Chair for if this needs to be updated', verbose_name='BioEHSC Handbook')),
                ('bioehsc_handbook_feedback_form', models.URLField(default='http://bit.ly/2017HandbookFeedback', help_text='Check with BioEHSC External Relations/Junior Chair/Senior Chair for if this needs to be updated', verbose_name='BioEHSC Handbook Feedback Form')),
                ('bioehsc_video_abstract_example_videos', models.URLField(default='https://drive.google.com/drive/folders/0Bx8PaywAIcv3blR1SUc1S2VTTkk?usp=sharing', help_text='Check with BioEHSC External Relations/Junior Chair/Senior Chair for if this needs to be updated', verbose_name='BioEHSC Video Abstract Examples')),
                ('bioehsc_resources_drive', models.URLField(default='https://drive.google.com/drive/folders/1ubcCDm1H4mnA7dr0h0xQH5i71kNEpYZC', help_text='TO BE UPDATED EACH SPRING', verbose_name='BioEHSC Resources Drive')),
                ('bioehsc_poster_examples', models.URLField(default='https://drive.google.com/drive/folders/0B9RoDuCJHR1JNUkzSTdObWJEU1k?usp=sharing', help_text='Check with BioEHSC External Relations/Junior Chair/Senior Chair for if this needs to be updated', verbose_name='BioEHSC Poster Examples')),
                ('campus_map', models.URLField(default='http://www.berkeley.edu/pdf/campusmap.pdf', verbose_name='BioEHSC Poster Examples')),
                ('bioehsc_petition_form', models.URLField(default='https://docs.google.com/forms/d/e/1FAIpQLSfM3yu38kLanIFioLKAAaRXlj6qXZSDcGGSFteQyJCuNkZjXw/viewform', help_text='TO BE UPDATED EACH SPRING', verbose_name='BioEHSC Petition Form')),
                ('bioehsc_liability_form', models.URLField(default='https://drive.google.com/file/d/198dAILPeBWKT6rcgQxmTcWxuw_v9mavU/view', help_text='TO BE UPDATED EACH SPRING', verbose_name='BioEHSC Liability Waiver')),
                ('bioehsc_photo_release_form', models.URLField(default='https://drive.google.com/open?id=1CBvzTBVndtPtMD5P0onhi6hEoRFKQrmR', help_text='TO BE UPDATED EACH SPRING', verbose_name='BioEHSC Photo Release Form')),
                ('bioehsc_medical_aut_form', models.URLField(default='https://drive.google.com/file/d/1MP60iwxeJtzkdVLr-jXYIiYXeqSb4c5m/view', help_text='TO BE UPDATED EACH SPRING', verbose_name='BioEHSC Medical Treatment Authorization Form')),
                ('bioehsc_school_auth_form', models.URLField(default='https://drive.google.com/file/d/1PKpKdV8CCUuoIIQTEn9Z4F0botWSy47M/view?usp=sharing', help_text='TO BE UPDATED EACH SPRING', verbose_name='BioEHSC School Authorization Form')),
                ('bioehsc_student_registration_form', models.URLField(default='http://bit.ly/2018EBBioEHSC', help_text='TO BE UPDATED EACH SPRING', verbose_name='BioEHSC Student Registration Form')),
                ('bioehsc_non_student_registration_form', models.URLField(default='http://bit.ly/2018BioEHSC_parent-coach_registration', help_text='TO BE UPDATED EACH SPRING', verbose_name='BioEHSC Visitor (Non-Student) Registration Form')),
            ],
        ),
    ]
