# Generated by Django 2.0 on 2019-01-01 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190101_0138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinkDatabase',
            new_name='ExternalURLDatabase',
        ),
    ]
