# Generated by Django 2.0 on 2019-01-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190101_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalurldatabase',
            name='bioehsc_fee_waiver',
            field=models.URLField(default='https://docs.google.com/forms/d/e/1FAIpQLSfvW-yC_GN-2SRFnFslzWe8Y8UkUG7_TteD4kakSyt6vHTuuQ/viewform?usp=sf_link', help_text='TO BE UPDATED EACH SPRING', verbose_name='BioEHSC Fee Waiver Form'),
        ),
        migrations.AddField(
            model_name='externalurldatabase',
            name='bioehsc_poster_link',
            field=models.URLField(default='https://drive.google.com/file/d/1tfhUF_EWWtxJ6qBu-9DPHNnoAiUcM_Bv/view', help_text='TO BE UPDATED EACH SPRING', verbose_name='BioEHSC Poster Advertisement'),
        ),
    ]
