# Generated by Django 2.0 on 2019-01-01 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_externalurldatabase_bioehsc_online_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalurldatabase',
            old_name='bioehsc_medical_aut_form',
            new_name='bioehsc_medical_auth_form',
        ),
    ]
