# Generated by Django 2.0 on 2019-01-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190101_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalurldatabase',
            name='bioe_day_rsvp_form',
            field=models.URLField(default='https://docs.google.com/forms/d/e/1FAIpQLSc_U00mF4xtgj3fhVTvOH2LIjijb6s66frEUvQ1zlDPxCsA1A/viewform', help_text='TO BE UPDATED EACH SPRING', verbose_name='BioE Day RSVP'),
        ),
    ]
