# Generated by Django 2.0 on 2019-01-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_externalurldatabase_bioe_day_informational_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalurldatabase',
            name='bioe_day_informational_poster',
            field=models.ImageField(default='home/committees/outreach/bioe_day_flyer.jpg', upload_to='home/committees/outreach/', verbose_name='BioE Day Informational Poster'),
        ),
    ]
