# Generated by Django 2.0 on 2019-01-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190104_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalurldatabase',
            name='bioe_day_informational_poster',
        ),
        migrations.AddField(
            model_name='externalurldatabase',
            name='bioe_day_flyer',
            field=models.ImageField(default='BioE-Day-Flyer-Fall-2018.jpg', help_text='TO BE UPDATED EACH SPRING', upload_to='', verbose_name='BioE Day Flyer'),
        ),
    ]
