# Generated by Django 2.0 on 2019-01-11 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190105_0114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExternalURLDatabase',
            new_name='SemesterSpecificInfo',
        ),
    ]
