# Generated by Django 2.0 on 2019-01-11 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190111_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semesterspecificinfo',
            options={'verbose_name': 'Semester Specific Information', 'verbose_name_plural': 'Semester Specific Information/Resources'},
        ),
    ]
