# Generated by Django 2.0 on 2019-01-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190111_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterspecificinfo',
            name='beacon_alum_registration',
            field=models.URLField(default='https://docs.google.com/forms/d/e/1FAIpQLSeAPkgZrGG2sjGNPn69yvydIr3_Ylv3OslriX7BCuPsdt5Qwg/viewform', help_text='Check with President if this needs updating', verbose_name='BEACON 2.0 Alumni Mentor Registration'),
        ),
    ]
