# Generated by Django 2.1.4 on 2019-01-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_semesterspecificinfo_beacon_alum_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesterspecificinfo',
            name='bioehsc_progress_form',
            field=models.URLField(default='http://bit.ly/2019WeeklyForms', help_text='TO BE UPDATED EACH SPRING', verbose_name='BioEHSC Mentor/Team Progress Form'),
        ),
    ]
