# Generated by Django 2.1.5 on 2019-03-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20190113_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterspecificinfo',
            name='bioehsc_faculty_volunteer',
            field=models.URLField(default='http://bit.ly/2019BioEHSCFaculty', help_text='TO BE UPDATED EACH SPRING', verbose_name='BioEHSC Faculty Volunteer Signup'),
        ),
        migrations.AddField(
            model_name='semesterspecificinfo',
            name='bioehsc_grad_volunteer',
            field=models.URLField(default='http://bit.ly/2019BioEHSCGradForm', help_text='TO BE UPDATED EACH SPRING', verbose_name='BioEHSC Grad Student/Postdoc Volunteer Signup'),
        ),
        migrations.AddField(
            model_name='semesterspecificinfo',
            name='bioehsc_industry_volunteer',
            field=models.URLField(default='http://bit.ly/2019BioEHSCIndustry', help_text='TO BE UPDATED EACH SPRING', verbose_name='BioEHSC Industry Volunteer Signup'),
        ),
        migrations.AddField(
            model_name='semesterspecificinfo',
            name='bioehsc_ugrad_volunteer',
            field=models.URLField(default='http://bit.ly/2019BioEHSCVolunteer', help_text='TO BE UPDATED EACH SPRING', verbose_name='BioEHSC Undergrad Volunteer Signup'),
        ),
    ]
