# Generated by Django 2.1.5 on 2019-03-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20190320_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterspecificinfo',
            name='bioehsc_volunteer_flyer',
            field=models.ImageField(default='BioE-Day-Flyer-Fall-2018.jpg', help_text='TO BE UPDATED EACH SPRING', upload_to='', verbose_name='BioEHSC Volunteer Flyer'),
        ),
    ]
