# Generated by Django 2.1.5 on 2019-08-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_semesterspecificinfo_bioehsc_volunteer_flyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesterspecificinfo',
            name='campus_map',
            field=models.ImageField(default='campusmap.jpg', help_text='TO BE UPDATED EACH SPRING', upload_to='', verbose_name='Campus Map'),
        ),
    ]
