# Generated by Django 2.1.5 on 2019-09-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20190829_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterspecificinfo',
            name='bioe_decal_flyer',
            field=models.ImageField(default='decal.pdf', help_text='TO BE UPDATED EACH FALL', upload_to='', verbose_name='Decal Flyer'),
        ),
    ]
