# Generated by Django 2.1.5 on 2019-09-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20190904_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesterspecificinfo',
            name='bioe_decal_flyer',
            field=models.URLField(default='https://drive.google.com/file/d/1--Z7TlbzwTaXhan4slS_kY8ajyi3RSHR/view?usp=sharingupload_to=', help_text='TO BE UPDATED EACH FALL', verbose_name='Decal Flyer'),
        ),
    ]
