# Generated by Django 2.1.5 on 2019-09-05 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20190904_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semesterspecificinfo',
            old_name='bioe_decal_flyer',
            new_name='decal_flyer',
        ),
    ]
