# Generated by Django 2.1.5 on 2020-01-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20190904_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterspecificinfo',
            name='bioehsc_ugrad_mentor',
            field=models.URLField(default='bit.ly/2020MentorRegistration', help_text='TO BE UPDATED EACH SPRING', verbose_name='BioEHSC Undergraduate Mentorship Form'),
        ),
    ]
