# Generated by Django 2.1.5 on 2021-01-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_semesterspecificinfo_video_and_project_abstract_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesterspecificinfo',
            name='bioehsc_handbook',
            field=models.URLField(default='https://drive.google.com/drive/folders/1XlELltEUiAxq3jSShb3MC5C5792RnTg-', help_text='Check with BioEHSC External Relations/Junior Chair/Senior Chair for if this needs to be updated', verbose_name='BioEHSC Handbook'),
        ),
        migrations.AlterField(
            model_name='semesterspecificinfo',
            name='bioehsc_handbook_feedback_form',
            field=models.URLField(default='http://bit.ly/2021HandbookFeedbackForm', help_text='Check with BioEHSC External Relations/Junior Chair/Senior Chair for if this needs to be updated', verbose_name='BioEHSC Handbook Feedback Form'),
        ),
        migrations.AlterField(
            model_name='semesterspecificinfo',
            name='bioehsc_poster_examples',
            field=models.URLField(default='https://drive.google.com/drive/folders/1scVsDs8-UHZ0A_-F7cyYcxtlUIsHFQwP?usp=sharing', help_text='Check with BioEHSC External Relations/Junior Chair/Senior Chair for if this needs to be updated', verbose_name='BioEHSC Poster Examples'),
        ),
        migrations.AlterField(
            model_name='semesterspecificinfo',
            name='bioehsc_poster_link',
            field=models.URLField(default='https://drive.google.com/file/d/1n_nqwnGkIek0e9mZ99Ljy00fTTIbMMxg/view', help_text='TO BE UPDATED EACH SPRING', verbose_name='BioEHSC Poster Advertisement'),
        ),
        migrations.AlterField(
            model_name='semesterspecificinfo',
            name='bioehsc_resources_drive',
            field=models.URLField(default='https://drive.google.com/drive/folders/1TUWwbkHCH69UbPqiSg82V75H4xd0YyHI?usp=sharing', help_text='TO BE UPDATED EACH SPRING', verbose_name='BioEHSC Resources Drive'),
        ),
        migrations.AlterField(
            model_name='semesterspecificinfo',
            name='bioehsc_video_abstract_example_videos',
            field=models.URLField(default='https://drive.google.com/drive/folders/187VRSJGoOPPYrBFnZ3-_36fxmOWcXYYa?usp=sharing', help_text='Check with BioEHSC External Relations/Junior Chair/Senior Chair for if this needs to be updated', verbose_name='BioEHSC Video Abstract Examples'),
        ),
    ]
