# Generated by Django 2.1.5 on 2021-01-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20210107_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesterspecificinfo',
            name='regular_application_form',
            field=models.URLField(default='https://tinyurl.com/Sp21application', help_text='TO BE UPDATED EACH SEMESTER', verbose_name='Regular Application Form'),
        ),
    ]
