# Generated by Django 2.1.5 on 2022-01-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20210125_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterspecificinfo',
            name='bioehsc_paperwork_documentation',
            field=models.URLField(default='https://drive.google.com/drive/folders/1yUP3MriPFu-jGxwegDQjIyiAk8-vmCBt?usp=sharing', verbose_name='BioEHSC Paperwork Documentation'),
        ),
        migrations.AddField(
            model_name='semesterspecificinfo',
            name='bioehsc_parent_release_form',
            field=models.URLField(default='https://bit.ly/2022BioEHSCParentRelease', help_text='TO BE UPDATED EACH SPRING', verbose_name='BioEHSC Parent Release Form'),
        ),
        migrations.AlterField(
            model_name='semesterspecificinfo',
            name='bioehsc_fee_waiver',
            field=models.URLField(default='https://forms.gle/6D2ZNDKvCGDfRFzy8', help_text='TO BE UPDATED EACH SPRING', verbose_name='BioEHSC Fee Waiver Form'),
        ),
        migrations.AlterField(
            model_name='semesterspecificinfo',
            name='bioehsc_liability_form',
            field=models.URLField(default='https://bit.ly/2022BioEHSCLiability', help_text='TO BE UPDATED EACH SPRING', verbose_name='BioEHSC Liability Waiver'),
        ),
        migrations.AlterField(
            model_name='semesterspecificinfo',
            name='bioehsc_online_application',
            field=models.URLField(default='https://bit.ly/2022BioEHSCApplication ', help_text='TO BE UPDATED EACH SPRING', verbose_name='BioEHSC Application'),
        ),
        migrations.AlterField(
            model_name='semesterspecificinfo',
            name='bioehsc_petition_form',
            field=models.URLField(default='https://bit.ly/2022BioEHSCPetition', help_text='TO BE UPDATED EACH SPRING', verbose_name='BioEHSC Petition Form'),
        ),
        migrations.AlterField(
            model_name='semesterspecificinfo',
            name='bioehsc_photo_release_form',
            field=models.URLField(default='https://bit.ly/2022BioEHSCPhotoRelease', help_text='TO BE UPDATED EACH SPRING', verbose_name='BioEHSC Photo Release Form'),
        ),
        migrations.AlterField(
            model_name='semesterspecificinfo',
            name='bioehsc_school_auth_form',
            field=models.URLField(default=' https://bit.ly/2022BioEHSCSchoolAuth', help_text='TO BE UPDATED EACH SPRING', verbose_name='BioEHSC School Authorization Form'),
        ),
        migrations.AlterField(
            model_name='semesterspecificinfo',
            name='bioehsc_student_registration_form',
            field=models.URLField(default='https://www.eventbrite.com/e/2022-bioehsctm-a-bioengineering-high-school-competition-tickets-242124660377', help_text='TO BE UPDATED EACH SPRING', verbose_name='BioEHSC Student Registration Form'),
        ),
    ]
