# Generated by Django 2.1.5 on 2022-01-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20220108_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesterspecificinfo',
            name='bioehsc_poster_link',
            field=models.URLField(default='https://drive.google.com/file/d/1UkgswaV25PVEWn-2xvtvKl53YWeTE4al/view?usp=sharing', help_text='TO BE UPDATED EACH SPRING', verbose_name='BioEHSC Poster Advertisement'),
        ),
    ]
