# Generated by Django 2.1.5 on 2022-01-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20220108_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesterspecificinfo',
            name='bioehsc_school_auth_form',
            field=models.URLField(default='https://bit.ly/2022BioEHSCSchoolAuth', help_text='TO BE UPDATED EACH SPRING', verbose_name='BioEHSC School Authorization Form'),
        ),
    ]
