# Generated by Django 2.1.5 on 2022-01-10 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20220109_0322'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='semesterspecificinfo',
            table='db.sqlite3',
        ),
    ]
