# Generated by Django 2.1.5 on 2022-01-10 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20220109_1616'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='semesterspecificinfo',
            table=None,
        ),
    ]
