# Generated by Django 2.1.5 on 2022-01-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20220109_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterspecificinfo',
            name='bioehsc_HS_flyer',
            field=models.ImageField(default='campusmap.jpg', help_text='TO BE UPDATED EACH SPRING', upload_to='', verbose_name='BioEHSC High School Recruitment Flyer'),
        ),
    ]
