# Generated by Django 2.1.5 on 2022-01-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_semesterspecificinfo_bioehsc_hs_flyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesterspecificinfo',
            name='bioehsc_HS_flyer',
            field=models.ImageField(default='2022_BioEHSC_HS_Flyer_1.jpg', help_text='TO BE UPDATED EACH SPRING', upload_to='', verbose_name='BioEHSC High School Recruitment Flyer'),
        ),
    ]
