# Generated by Django 2.1.4 on 2018-12-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0004_auto_20181221_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='image',
            field=models.ImageField(default='static/images/<django.db.models.fields.charfield>.jpg', upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='term',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Fall', 'Fall')], max_length=5),
        ),
    ]
