# Generated by Django 2.1.4 on 2018-12-21 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0005_auto_20181221_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='image',
        ),
    ]
