# Generated by Django 2.1.4 on 2018-12-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0007_auto_20181221_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='positions',
            field=models.ManyToManyField(related_name='officers', to='officers.Position'),
        ),
    ]
