# Generated by Django 2.0 on 2018-12-24 22:08

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0009_officer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='static/headshots/'),
        ),
    ]
