# Generated by Django 2.0 on 2018-12-24 22:10

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0010_auto_20181224_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='officers/static/headshots/'),
        ),
    ]
