# Generated by Django 2.0 on 2018-12-27 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('officers', '0012_auto_20181225_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='name',
        ),
        migrations.AddField(
            model_name='officer',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
