# Generated by Django 2.0 on 2018-12-27 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('officers', '0013_auto_20181227_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_officer', models.BooleanField(default=False, verbose_name='Officer Status')),
                ('is_candidate', models.BooleanField(default=False, verbose_name='Candidate Status')),
                ('image', imagekit.models.fields.ProcessedImageField(default='headshots/default.jpg', upload_to='headshots/')),
                ('positions', models.ManyToManyField(related_name='officers', to='officers.Position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('officers', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='officer',
            name='positions',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Officer',
        ),
    ]
