# Generated by Django 2.0 on 2018-12-31 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0019_auto_20181231_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dues_1',
        ),
    ]
