# Generated by Django 2.0 on 2018-12-31 20:00

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0020_remove_userprofile_dues_1'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='candidaterequirement',
            managers=[
                ('requirements', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='candidaterequirement',
            name='requirement',
            field=models.CharField(choices=[('DUES 1', 'Membership Dues Part 1'), ('DUES 2', 'Membership Dues Part 2'), ('PHOTO', 'Photoshoot'), ('RESUME/LINKEDIN', 'Resume and Linkedin Workshop'), ('PRODEV EVENT', 'Professional Development Event'), ('ACA EVENT', 'Academic Event'), ('OUTREACH EVENT', 'Outreach Event'), ('SOC EVENT 1', 'Social Event 1'), ('SOC EVENT (LRG FAM)', 'Social Event 2 with your large family'), ('CHALLENGE NIGHT', 'Candidate Challenge Night'), ('RETREAT', 'Candidate Retreat'), ('GM 1', 'General Meeting 1'), ('GM 2', 'General Meeting 2'), ('GM 3', 'General Meeting 3'), ('BANQUET', 'End of the Year Banquet')], default=None, max_length=50),
            preserve_default=False,
        ),
    ]
