# Generated by Django 2.0 on 2018-12-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0021_auto_20181231_2000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CandidateRequirement',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='academic_event',
            field=models.BooleanField(default=False, verbose_name='Academic Event'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='banquet',
            field=models.BooleanField(default=False, verbose_name='End of the Year Banquet'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='candidate_challenge',
            field=models.BooleanField(default=False, verbose_name='Candidate Challenge Night'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dues_1',
            field=models.BooleanField(default=False, verbose_name='Membership Dues Part 1'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dues_2',
            field=models.BooleanField(default=False, verbose_name='Membership Dues Part 2'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='family_dinner',
            field=models.BooleanField(default=False, verbose_name='Family Dinner'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gm_1',
            field=models.BooleanField(default=False, verbose_name='General Meeting 1'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gm_2',
            field=models.BooleanField(default=False, verbose_name='General Meeting 2'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gm_3',
            field=models.BooleanField(default=False, verbose_name='General Meeting 3'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='outreach_event',
            field=models.BooleanField(default=False, verbose_name='Outreach Event'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photoshoot',
            field=models.BooleanField(default=False, verbose_name='Photoshoot'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prodev_event',
            field=models.BooleanField(default=False, verbose_name='Professional Development Event'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume_linkedin',
            field=models.BooleanField(default=False, verbose_name='Résumé and LinkedIn Workshop'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='retreat',
            field=models.BooleanField(default=False, verbose_name='Candidate Retreat'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_event_1',
            field=models.BooleanField(default=False, verbose_name='Social Event 1'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_event_2',
            field=models.BooleanField(default=False, verbose_name='Social Event 2 with your large family'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='officers', to='officers.Position'),
        ),
    ]
