# Generated by Django 2.0 on 2018-12-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0022_auto_20181231_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notes',
            field=models.TextField(blank=True, help_text="Enter any additional admin notes for the user; i.e. 'Academic Event candidate requirement fulfilled on MM/DD/YYYY with a makeup event, marked as completed'"),
        ),
    ]
