# Generated by Django 2.0 on 2019-01-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0025_auto_20190105_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='beacon_bio',
            field=models.URLField(blank=True, help_text='Ex: BioE major, EECS minor, working at _______. Feel free to contact me or add me on LinkedIn.', verbose_name='Bio for Alumni (BEACON 2.0)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_beacon_alumnus',
            field=models.BooleanField(default=False, verbose_name='BEACON 2.0 Alumnus'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn Profile'),
        ),
    ]
