# Generated by Django 2.0 on 2019-01-11 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0027_auto_20190110_0054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'Officer/Candidate User Profiles'},
        ),
    ]
