# Generated by Django 2.0 on 2019-01-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0028_auto_20190111_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='beacon_bio',
            field=models.URLField(blank=True, help_text='Ex: BioE major, EECS minor,     former BioEHS [position] in [semester, year], part of [professor name & research area] lab.     Currently working at _______. Feel free to contact me or add me on LinkedIn.', verbose_name='Bio for Alumni (BEACON 2.0)'),
        ),
    ]
