# Generated by Django 2.0 on 2019-01-11 21:22

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0030_auto_20190111_1150'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('userprofiles', django.db.models.manager.Manager()),
            ],
        ),
    ]
