# Generated by Django 2.1.5 on 2019-09-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0032_auto_20190306_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ccc',
            field=models.BooleanField(blank=True, default=False, verbose_name='Cross Committee Conference'),
        ),
    ]
