# Generated by Django 2.1.5 on 2019-09-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0033_userprofile_ccc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='resume_linkedin',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_workshop',
            field=models.BooleanField(blank=True, default=False, verbose_name='Linkedin Workshop'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume_submission',
            field=models.BooleanField(blank=True, default=False, verbose_name='Résumé Submission'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume_workshop',
            field=models.BooleanField(blank=True, default=False, verbose_name='Résumé Workshop'),
        ),
    ]
