# Generated by Django 2.1.5 on 2021-04-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0042_auto_20210417_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='buddy_hangout',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='family_hangout',
            field=models.BooleanField(blank=True, default=False, verbose_name='Family Hangout'),
        ),
    ]
