# Generated by Django 2.1.5 on 2021-04-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0044_auto_20210417_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='buddy_hangout',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='buddy_hangouts',
            field=models.BooleanField(blank=True, default=False, verbose_name='Buddy Hangouts'),
        ),
    ]
