# Generated by Django 2.1.5 on 2022-04-07 02:02

from django.db import migrations, models
import officers.models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0048_auto_20220406_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='alumnus_last_contacted',
            field=models.TextField(blank=True, help_text='Last contacted date, need to manually', verbose_name=officers.models.Semester),
        ),
    ]
