# Generated by Django 2.1.5 on 2022-04-07 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0049_auto_20220406_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='alumnus_last_contacted',
            field=models.ForeignKey(help_text='Last contacted date, need to manually', null=True, on_delete=django.db.models.deletion.CASCADE, to='officers.Semester'),
        ),
        
    ]
