# Generated by Django 2.1.5 on 2022-11-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0050_auto_20220406_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='project_event',
            field=models.BooleanField(blank=True, default=False, verbose_name='Project Event'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_event_3',
            field=models.BooleanField(blank=True, default=False, verbose_name='Social Event 3'),
        ),
    ]
