# Generated by Django 2.1.5 on 2022-11-26 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0051_auto_20221126_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='buddy_hangouts',
        ),
    ]
