# Generated by Django 2.1.5 on 2022-11-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0052_remove_userprofile_buddy_hangouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='buddy_hangouts',
            field=models.BooleanField(blank=True, default=False, verbose_name='Buddy Hangouts'),
        ),
    ]
