# Generated by Django 2.1.4 on 2019-01-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Sponsor Name here', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
