# Generated by Django 2.1.4 on 2019-01-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0002_auto_20190109_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(help_text='Enter Sponsor Name here.', max_length=100),
        ),
    ]
