# Generated by Django 2.1.4 on 2019-01-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0003_auto_20190109_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='description',
            field=models.TextField(help_text='Enter information about the sponsor here/', null=True),
        ),
    ]
