# Generated by Django 2.1.4 on 2019-01-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0005_auto_20190109_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='model_pic',
            field=models.ImageField(default='media/default.png', upload_to='media/'),
        ),
    ]
