# Generated by Django 2.1.4 on 2019-01-10 18:51

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0006_sponsor_model_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='description',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='year',
            field=models.PositiveSmallIntegerField(default=2019),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='model_pic',
            field=imagekit.models.fields.ProcessedImageField(default='media/default.png', upload_to='media/'),
        ),
    ]
