# Generated by Django 2.1.4 on 2019-01-14 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0007_auto_20190110_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='model_pic',
            new_name='sponsor_pic',
        ),
    ]
