# Generated by Django 2.1.4 on 2019-01-14 02:47

from django.db import migrations, models
import django.db.models.manager
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0008_auto_20190113_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=2019)),
            ],
            options={
                'ordering': ['year'],
            },
            managers=[
                ('years', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_pic',
            field=imagekit.models.fields.ProcessedImageField(default='sponsors/default.png', upload_to='sponsors/'),
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='year',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='year',
            field=models.ManyToManyField(blank=True, to='industrial.Year'),
        ),
    ]
