# Generated by Django 2.1.4 on 2019-01-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0009_auto_20190113_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='year',
            field=models.ManyToManyField(to='industrial.Year'),
        ),
    ]
