# Generated by Django 2.1.4 on 2019-01-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0010_auto_20190113_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
