# Generated by Django 2.1.4 on 2019-01-14 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0011_sponsor_link'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='year',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='sponsor',
            old_name='sponsor_pic',
            new_name='pic',
        ),
    ]
