# Generated by Django 2.1.4 on 2019-01-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0012_auto_20190113_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='year',
            field=models.ManyToManyField(blank=True, to='industrial.Year'),
        ),
    ]
