# Generated by Django 2.1.4 on 2019-01-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0013_auto_20190113_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='year',
            field=models.ManyToManyField(blank=True, related_name='sponsors', to='industrial.Year'),
        ),
    ]
