# Generated by Django 2.1.5 on 2020-01-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0016_auto_20190113_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.PositiveSmallIntegerField(default=2020),
        ),
    ]
