# Generated by Django 2.1.5 on 2023-01-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0019_auto_20220104_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.PositiveSmallIntegerField(default=2023),
        ),
    ]
